### ISSUE TITLE
Attach to X root window

### ISSUE THREAD

**Issue by reyqn** [jtsiomb/colcycle#1]
Hi, I'm trying to use this with xwinwrap so I can use this kind of image as an animated wallpaper.

In vlc or mpv for example, from what I understand, you can attach to the X root window with the --wid=WID (mpv) or --drawable-xid WID (vlc).

I tried to edit the opengl backend of colcycle to do the same, but I don't think I know enough about X and opengl.

Do you have any idea how I could do this?

**Comment by jtsiomb** [comment]
You can't do that easily with colcycle as it is, because I'm using glut for window creation, which doesn't provide this kind of flexibility. But I have done exactly what you're looking for in my new xlivebg project: https://github.com/jtsiomb/xlivebg.

It's a live wallpaper system based on a plugin architecture, and one of the early plugins I already have working, is based on colcycle. Check out a video capture here: http://mutantstargoat.com/~nuclear/tmp/xlivebg_colcycle_video.mp4

Try using xlivebg, and if you have any issues with it, let me know in the xlivebg issues tracker. I'm closing this issue here.
